### ISSUE TITLE
Upgrade Project to Latest OpenJDK and Gradle Versions

### ISSUE THREAD

**Issue by dbschema-pro** [groovyfx-project/groovyfx#70]
Is it possible to make this project compatible with the latest OpenJDK versions and Gradle?

If I upgrade, I am getting this error:
```
C:\Temp\groovyfx\src\main\groovy\groovyx\javafx\canvas\FillArcOperation.groovy: Could not find class for Transformation Processor groovyx.javafx.beans.FXBindableASTTransformation declared by groovyx.javafx.beans.FXBindable
```

I previously fixed another issue by changed in build.gradle from 
```
sourceSets {
    demo {
        compileClasspath += sourceSets.main.output + configurations.compile
        runtimeClasspath += sourceSets.main.output
...
```
to 
```
sourceSets {
    demo {
        compileClasspath += sourceSets.main.output + configurations.runtimeClasspath
        runtimeClasspath += sourceSets.main.output
```

**Comment by ambastos** [comment]
I have a similar error using Intellij and more recent version of Gradle than this project. But appears nobody answer yet. I change some lines in build.gradle, but I the error is very similar of yours.. :(
I really like to create a project using this project, because it appears to be far easier then codifying in Java

**Comment by dbschema-pro** [comment]
I created a issue also for Groovy, and they answered telling I should debug the compilation of Groovy, specifc on class org.codehaus.groovy.transform.ASTTransformationCollectorCodeVisitor:239, with the try to find the actual classpath. Probably the classpath in the build.gradle should be fixed.

**Comment by dbschema-pro** [comment]
I succeeded to migrate the project to OpenJDK 21. Here is a fork: 
https://github.com/wise-coders/groovyfx
Please test and review it. I will make a pull request to the original project.

**Comment by ambastos** [comment]
Thanks! But still doesnt work for me. I first try with the Java 21 and it do not build and with Java 17. With Java 17 I have kind of same error, and with Java 21 I believe it's incompatible version of the files.. 
     `* What went wrong:
Could not open cp_settings generic class cache for settings file '/media/ambastos/Documents/home/ambastos/projects/others/java/new-groovyfx/settings.gradle' (/home/ambastos/.gradle/caches/7.6/scripts/ah25nx35rvt4fnjlg96jdg28f).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
`

        and with Java 17:

`> Task :compileAstGroovy
Note: /media/ambastos/Documents/home/ambastos/projects/others/java/new-groovyfx/src/ast/groovy/groovyx/javafx/beans/FXBindableASTTransformation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /media/ambastos/Documents/home/ambastos/projects/others/java/new-groovyfx/src/ast/groovy/groovyx/javafx/beans/FXBindableASTTransformation.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileGroovy
/media/ambastos/Documents/home/ambastos/projects/others/java/new-groovyfx/src/main/groovy/groovyx/javafx/binding/GroovyClosureProperty.java:152: warning: [removal] AccessController in java.security has been deprecated and marked for removal
            Closure closureLocalCopy = java.security.AccessController.doPrivileged(new PrivilegedAction<Closure>() {
                                                    ^
Note: /media/ambastos/Documents/home/ambastos/projects/others/java/new-groovyfx/src/main/groovy/groovyx/javafx/binding/GroovyClosureProperty.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :compileTestGroovy
startup failed:
/media/ambastos/Documents/home/ambastos/projects/others/java/new-groovyfx/src/test/groovy/groovyx/javafx/beans/FXBindableTest.groovy: Could not find class for Transformation Processor groovyx.javafx.beans.FXBindableASTTransformation declared by groovyx.javafx.beans.FXBindable

1 error
`

I just using the gradlew command, not using a gradle installation on my machine. I notice that It try to use gradle 7.6 version..

**Comment by dbschema-pro** [comment]
I don't know how to help in this case. I cannot reproduce this issue. 
The idea behind my fix was to prepare a class in a separate source. The compiled class was required to compile the next source.
My fixes are under https://github.com/wise-coders/groovyfx

**Comment by ambastos** [comment]
One thing could help... What gradle version are you using?

**Comment by dbschema-pro** [comment]
I use Gradle 7.6.
I got the project working. I pushed my changes into 
https://github.com/wise-coders/groovyfx

I created also a pull request to the original project, but nobody is answering.
